### ISSUE TITLE
The React example does not work

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [joellord/frontend-containers#1]
This is a great article and something I have been looking for in the past. Sadly I cannot get the React example to work (I haven't tried the others.)

**Steps to reproduce**

1. Checkout the repository
2. cd into the "react-project" folder
3. Execute `docker build -t front-end .`
4. Execute `docker run -d -p 8080:80 --rm --name front -e ENV=prod -e BASE_URL=/api frontend`
5. Navigate to http://localhost:8080/

**Expected behavior**
The values defined as environmental variables in the `docker run` command are displayed.

**Actual behavior**
![Screenshot from 2021-06-01 17-44-40](https://user-images.githubusercontent.com/46844303/120360838-1e8ef100-c301-11eb-8f1d-76e8699ce09f.png)

**Further remarks**
When starting the container the following message is printed: `cat: '/usr/share/nginx/html/static/js/*.json': No such file or directory`. The message makes sense there is no `config.json` file present.
I must confess that I also don't understand how the config.json file would end up in there.

I also tried adding the `config.json` file after the container was created using `docker cp src/config.json front:/usr/share/nginx/html/static/js/config.json` and restarting the container. This also didn't change whats shown in the UI.

Replacing the variables works. Using a config.json file with the following content (again directly copied into the container)
```
{
  "ENV": "$ENV",
  "BASE_URL": "$BASE_URL"
}
```
leads to a config.json file with the values replaced. But they are still not shown in the UI.

**Comment by joellord** [comment]
Looking at the steps you used, your might be trying to run the wrong container.

> Execute `docker build -t front-end .`
> Execute `docker run -d -p 8080:80 --rm --name front -e ENV=prod -e BASE_URL=/api frontend`

Try changing that second line to 
`docker run -d -p 8080:80 --rm --name front -e ENV=prod -e BASE_URL=api frontend`

**Comment by ChristianHuff-DEV** [comment]
Thank you.
I used the instructions from [here](https://developers.redhat.com/blog/2021/03/04/making-environment-variables-accessible-in-front-end-containers#create_a_skeleton_application) and didn't pay enough attention. There it uses "front-end" for the build and "frontend" when running the container.

I must have mixed up the commands building both images but running the wrong one.

Using the correct `docker run` command produces the correct output. Inspecting the *...chunk.js* I can the the replaced values.
But now the console puts out the following error:
```
Uncaught SyntaxError: missing ) in parenthetical
```
My best guess is that *start-nginx.sh* does something to invalidate the JavaScript code. Once I commend out the code replacing the variables the UI is shown. (Of course without replacing the variables.)

**Comment by ChristianHuff-DEV** [comment]
Thank you for this article. It's a shame how hard it is to "build once run anywhere" with React. (Your Vue example works perfectly.)
I guess replacing values inside the generated JavaScript code comes with a certain risk.

For now I'll go back to building a dedicated release for each environment.
